import { Injectable } from "@angular/core";
import { InMemoryDbService } from "angular-in-memory-web-api";

@Injectable({ providedIn: 'root' })
export class InMemoryInformacionService implements InMemoryDbService {
  createDb() {
    const JUGADORES = [
      { id: 1, ranking: 1, nacionalidad: "Serbia", nombre: "Novak Djokovic", edad: 31, puntos: 11070, torneosJugados: 18, foto: "./assets/jugadores/NovakDjokovic.JPG", biografia: "Novak Djokovic nació el 22 de mayo de 1987, en Belgrado, Yugoslavia. Su padre se llama Srdjan, de origen serbio, gran jugador de tenis de mesa y destacado en el esquí, y su madre Dijana, es de origen croata. Tiene dos hermanos menores, Marko y Djordje, que también son jugadores de tenis con aspiraciones profesionales.", torneos: "Ha ganado un total de 15 Grand Slams ( Australian Open, Roland Garros, Wimbledon y Us Open) por detrás de Roger Federer con 20 y Rafael Nadal con 17. El Abierto de Australia en siete ocasiones, (2008, 2011, 2012,​ 2013,​ 2015, 2016 y 2019)​. Campeonato de Wimbledon en cuatro ocasiones (2011, 2014 , 2015, y 2018 ) el Abierto de Estados Unidos en tres ocasiones (2011​ y 2015 y 2018), y el Torneo de Roland Garros en 2016", curiosidad: "Djokovic también es conocido por su gran sentido del humor fuera de las canchas y por las imitaciones de sus compañeros, muchos de quienes son sus amigos. Esto se hizo evidente para el mundo del tenis después de su victoria en 2007 en el Abierto de Estados Unidos en los cuartos de final frente a Carlos Moyá, donde entretuvo a la audiencia con imitaciones de Rafael Nadal y María Sharápova." },
      { id: 2, ranking: 2, nacionalidad: "España", nombre: "Rafael Nadal", edad: 32, puntos: 8725, torneosJugados: 16, foto: "./assets/jugadores/RafaelNadal.JPG", biografia: "Nació el 3 de junio de 1986 en Manacor, Isla de Mallorca, Baleares, España. Sus padres son Ana María Parera y Sebastián Nadal; tiene una hermana menor, María Isabel. Nació en una familia de deportistas, su tío Miguel Ángel Nadal fue jugador de fútbol del FC Barcelona y del RCD Mallorca y su tío Toni Nadal había sido jugador de tenis. Fue con éste con quien se inició con los primeros golpes de raqueta a los tres años de edad.", torneos: "Ha conseguido el Torneo de Roland Garros en once ediciones, siendo el tenista que más veces lo ha ganado (en 2005, 2006, 2007,​ 2008,​ 2010,​ 2011,​ 2012,​ 2013,​ 2014, 2017 y 2018), el Campeonato de Wimbledon en dos ocasiones (2008​ y 2010,​ y finalista en 2006, 2007​ y 2011),​ el Abierto de Australia en una ocasión (2009, y finalista en 2012, 2014, 2017 y 2019) y el Abierto de Estados Unidos en tres ocasiones (2010, 2013 y 2017, y finalista en 2011).", curiosidad: "Tras haber ganado su primer Roland Garros y suficiente dinero como para considerarse millonario, mantenía su residencia en un apartamento compartido con su hermana pequeña en Manacor, en el mismo edificio que sus abuelos, sus tíos y sus padres." },
      { id: 3, ranking: 3, nacionalidad: "Alemania", nombre: "Alexander Zverev", edad: 22, puntos: 6040, torneosJugados: 20, foto: "./assets/jugadores/AlexanderZverev.JPG", biografia: "Alexander \"Sascha\" Zverev (Hamburgo, 20 de abril de 1997) es un tenista alemán de ascendencia rusa. Es hermano menor del también tenista Mischa Zverev (n. 1987). Su padre, Aleksandr Zvérev Sr., es un ex-tenista soviético que compitió en la Copa Davis defendiendo a la Unión Soviética y es el actual entrenador de Alexander.", torneos: "En 2017 ganó su primer Masters 1000 en Roma que le permitió entrar al top 10 por primera vez en su carrera.", curiosidad: " Al terminar la temporada 2015 en el puesto 81º del mundo con solo 18 años, fue premiado por la ATP como el tenista más joven en el Top 100." },
      { id: 4, ranking: 4, nacionalidad: "Suiza", nombre: "Roger Federer", edad: 37, puntos: 5590, torneosJugados: 17, foto: "./assets/jugadores/RogerFederer.JPG", biografia: "Roger Federer nació el 8 de agosto de 1981 en Binningen, Suiza, pequeña población cercana a la ciudad de Basilea; pero se crio en Riehen y sobre todo en Münchenstein. Es hijo de Lynette y Robert Federer, tiene una hermana mayor llamada Diana.", torneos: "Roger Federer ha logrado récords de ocho títulos del Campeonato de Wimbledon, seis del Abierto de Australia y cinco del Abierto de Estados Unidos, así como un título del Torneo de Roland Garros. Es uno de los ocho tenistas que ha logrado vencer en los cuatro Grand Slams. También ostenta el mejor registro en el número de finales de Grand Slam jugadas: 30, diez de éstas consecutivas, entre la final de Wimbledon 2005 y el Abierto de Estados Unidos 2007", curiosidad: "La mayoría de los analistas deportivos, autoridades deportivas y críticos del tenis,​ la prensa especializada, así como también los jugadores y exjugadores, consideran a Federer como el «mejor tenista de la historia»." },
      { id: 5, ranking: 5, nacionalidad: "Austria", nombre: "Dominic Thiem", edad: 25, puntos: 4765, torneosJugados: 24, foto: "./assets/jugadores/DominicThiem.JPG", biografia: "Dominic Thiem (Wiener Neustadt, 3 de septiembre de 1993) es un jugador de tenis austriaco.", torneos: "Ha logrado llegar a la cuarta ronda de todos los Torneos de Grand Slam, a la final de Roland Garros y a 3 finales de Masters 1000, ganando la final de Indian Wells 2019, proclamándose vencedor frente a Roger Federer y alzando así el primer Masters 1000 de su carrera.", curiosidad: "Por talento, capacidad y potencia sobre la arcilla, Dominic Thiem es el llamado a ser el sucesor de Rafael Nadal en esta superficie." },
      { id: 6, ranking: 6, nacionalidad: "Japon", nombre: "Kei Nishikori", edad: 29, puntos: 4200, torneosJugados: 23, foto: "./assets/jugadores/KeiNishikori.JPG", biografia: "Kei Nishikori (Matsue, Prefectura de Shimane, Japón, 29 de diciembre de 1989). Nishikori comenzó a jugar a los cinco años. Su madre, Eri, es maestra de piano; su padre, Kiyoshi, es ingeniero. Tiene una hermana mayor, llamada Reina graduada de la universidad y que trabaja en Tokio.", torneos: "Ha competido en un total de 26 finales a lo largo de toda su carrera, saliendo victorioso en 12 de ellas. 6 torneos ganados del ATP World Tour 500 y 6 del ATP World Tour 250.", curiosidad: "Se mudó de Shimane, Japón a Estados Unidos a los 14 años para entrenar en la Academia IMG Bollettieri en Florida y no hablaba una palabra de inglés cuando llegó." },
      { id: 7, ranking: 7, nacionalidad: "Sudafrica", nombre: "Kevin Anderson", edad: 32, puntos: 4115, torneosJugados: 18, foto: "./assets/jugadores/KevinAnderson.JPG", biografia: "Kevin Anderson (Johannesburgo, Sudáfrica, 18 de mayo de 1986) es un jugador de tenis sudafricano. Anderson comenzó a jugar tenis a los 6 años y fue competitivo en carreras de 800 metros en la escuela.", torneos: "Kevin Anderson ha participado en múltiples torneos, siendo finalista en 13 ocasiones y saliendo victorioso en 6 de ellas; 5 en el ATP World Tour 250 y 1 vez en ATP World Tour 500.", curiosidad: "Anderson toca la guitarra y es fanático de la banda de rock británica Dire Straits y Mark Knopfler. Su programa de televisión favorito es House of Cards." },
      { id: 8, ranking: 8, nacionalidad: "Grecia", nombre: "Stefanos Tsitsipas", edad: 20, puntos: 3240, torneosJugados: 28, foto: "./assets/jugadores/StefanosTsitsipas.JPG", biografia: "Stefanos Tsitsipas nació en Atenas el 13 de agosto de 1998. Su padre, Apostolos, es griego y es su entrenador. Su madre, la extenista Julia Apostoli, es rusa. Es nieto de Sergei Salnikov, un jugador y entrenador de fútbol que ganó la medalla de oro en el torneo de fútbol de los Juegos Olímpicos de 1956.", torneos: "A pesar de su corta edad, Stefanos ha logrado consagrarse campeón en tres torneos individuales. 2 veces en el ATP World Tour 250 y en el Next Gen ATP Finals.", curiosidad: "Tsitsipas tiene un aire filosófico en su manera de hablar. Posee, además, una inclinación por el arte y la creatividad. Es una suerte de fotógrafo aficionado y edita su propio canal de YouTube, en el que relata sus experiencias de vida." },
      { id: 9, ranking: 9, nacionalidad: "Argentina", nombre: "Juan Martin del Potro", edad: 30, puntos: 3225, torneosJugados: 14, foto: "./assets/jugadores/JuanMartinDelPotro.JPG", biografia: "Juan Martín nació en Tandil, provincia de Buenos Aires, el 23 de septiembre de 1988.11​ Su padre, Daniel del Potro, es veterinario y fue jugador de rugby semi-profesional en Argentina.", torneos: "Siendo uno de los deportistas argentinos más reconocidos de la época actual, Juan Martín del Potro ha logrado coronarse campeón en 22 ocasiones de las 35 finales a las que ha logrado llegar.", curiosidad: "Aparte del tenis le gusta jugar al fútbol. Es amigo íntimo de Martín Palermo e hincha reconocido del Club Atlético Boca Juniors, además confesó que le gustaba un poco más el fútbol que el tenis. Es tan fanático del club argentino que en Wimbledon 2012 pidió atrasar su partido de segunda ronda para poder ver la final de la Copa Libertadores 2012 ante Corinthians." },
      { id: 10, ranking: 10, nacionalidad: "Estados Unidos", nombre: "John Isner", edad: 33, puntos: 3085, torneosJugados: 23, foto: "./assets/jugadores/JohnIsner.JPG", biografia: "John Robert Isner (Greensboro, Carolina del Norte, 26 de abril de 1985). Tiene dos hermanos mayores, Nathan y Jordania. Isner comenzó a jugar tenis a los 9 años bajo la tutela de Oscar Blacutt y Stephens Rob en la Academia de Tenis Carolina.", torneos: "Ganador de una cantidad considerable de torneos ATP World Tour 250 (13 veces ganador), el jugados estado unidense ha conseguido un total de 14 torneos individuales en su palmarés.", curiosidad: "Es reconocido principalmente por haber sido el ganador del partido más largo de la historia celebrado en el Campeonato de Wimbledon 2010." },
      { id: 11, ranking: 11, nacionalidad: "Croacia", nombre: "Marin Cilic", edad: 30, puntos: 3015, torneosJugados: 18, foto: "./assets/jugadores/MarinCilic.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 12, ranking: 12, nacionalidad: "Rusia", nombre: "Karen Khachanov", edad: 22, puntos: 2810, torneosJugados: 24, foto: "./assets/jugadores/KarenKhachanov.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 13, ranking: 13, nacionalidad: "Croacia", nombre: "Borna Coric", edad: 22, puntos: 2345, torneosJugados: 20, foto: "./assets/jugadores/BornaCoric.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 14, ranking: 14, nacionalidad: "Rusia", nombre: "Daniil Medvedev", edad: 23, puntos: 2295, torneosJugados: 27, foto: "./assets/jugadores/DaniilMedvedev.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 15, ranking: 15, nacionalidad: "Canada", nombre: "Milos Raonic", edad: 28, puntos: 2140, torneosJugados: 21, foto: "./assets/jugadores/MilosRaonic.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 16, ranking: 16, nacionalidad: "Italia", nombre: "Marco Cecchinato", edad: 26, puntos: 2021, torneosJugados: 29, foto: "./assets/jugadores/MarcoCecchinato.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 17, ranking: 17, nacionalidad: "Georgia", nombre: "Nikoloz Basilashvili", edad: 27, puntos: 1930, torneosJugados: 29, foto: "./assets/jugadores/NikolozBasilashvili.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 18, ranking: 18, nacionalidad: "Italia", nombre: "Fabio Fognini", edad: 31, puntos: 1885, torneosJugados: 25, foto: "./assets/jugadores/FabioFogini.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 19, ranking: 19, nacionalidad: "Francia", nombre: "Gael Monfils", edad: 32, puntos: 1875, torneosJugados: 21, foto: "./assets/jugadores/GaelMonfils.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 20, ranking: 20, nacionalidad: "Canada", nombre: "Denis Shapovalov", edad: 19, puntos: 1820, torneosJugados: 27, foto: "./assets/jugadores/DenisShapovalov.JPG", biografia: "", torneos: "", curiosidad: "" }
    ];
    const JUGADORAS = [
      { id: 1, ranking: 1, nacionalidad: "Japon", nombre: "Naomi Osaka", edad: 21, foto: "./assets/jugadoras/NaomiOsaka.JPG", biografia: "Naomi Osaka (Osaka, Japón; 16 de octubre de 1997) es una jugadora de tenis. Tiene doble nacionalidad (estadounidense y japonesa), reside permanentemente en Florida, Estados Unidos, pero compite representando a Japón. Hija de padre haitiano y madre japonesa. Es la hermana menor de Mari Osaka, quien es también jugadora de tenis profesional.", torneos: "A pesar de su corta carrera incursionando en el amplio círculo del tenis profesional (5 años), Naomi ha logrado obtener 3 títulos de alto renombre, 2 Gran Slam y el Premier Mandatory.", curiosidad: "En el primer Grand Slam de 2019, el Australian Open, Osaka alcanzó su segundo título de esta categoría, y de forma consecutiva. Derrotó a Petra Kvitova en la final por 7-6, 5-7, 6-4 y, además, alcanzó por primera vez en su carrera el primer puesto del escalafón mundial. Se convertiría así en la 26ª número 1 de la historia, primera japonesa en lograrlo, así como también, la primera asiática en lograrlo." },
      { id: 2, ranking: 2, nacionalidad: "Rumania", nombre: "Simona Halep", edad: 27, foto: "./assets/jugadoras/SimonaHalep.JPG", biografia: "Simona Halep (Constanza, Rumania, 27 de septiembre de 1991). El padre de Halep, Stere, dirige una fábrica de queso y leche.​ Simona comenzó a jugar al tenis a los cuatro años, emulando a su hermano mayor.", torneos: "Ganadora en una ocasión de Roland Garros, siendo este uno de los 18 torneos avalados por la WTA que ha ganado en su carrera. Además ha ganado seis torneos de categorías juveniles.", curiosidad: "En una entrevista posterior a un partido con Serena Williams en Wimbledon 2011, la tenista estadounidense comentó que Halep \"sirve bien para su altura... Tiene mucho poder en su servicio\"." },
      { id: 3, ranking: 3, nacionalidad: "Republica Checa", nombre: "Petra Kvitova", edad: 29, foto: "./assets/jugadoras/PetraKvitova.JPG", biografia: "Petra Kvitová (Bílovec, República Checa, 8 de marzo de 1990). Petra Kvitová es hija de Jiří Kvita, un maestro de escuela,3​4​ y Pavla Kvitová. Nació en Bílovec, región de Moravia-Silesia, Checoslovaquia (ahora República Checa). Ella tiene dos hermanos mayores, Jiří, un ingeniero, y Libor, un maestro de escuela. Su padre Jiří la introdujo al tenis.", torneos: "De manera individual, la jugadora checa ha logrado conseguir un total de 27 torneos. Entre estos son reconocibles 2 torneos de Grand Slam, 1 WTA Tour Championship y 1 WTA Elite Trophy. ", curiosidad: "Durante su infancia, admiró a la jugadora checa/estadounidense Martina Navratilova. Kvitová se entrenó en su ciudad natal de Fulnek hasta la edad de 16 años, y un instructor lo alentó a seguir una carrera profesional en el tenis." },
      { id: 4, ranking: 4, nacionalidad: "Republica Checa", nombre: "Karolina Pliskova", edad: 27, foto: "./assets/jugadoras/KarolinaPliskova.JPG", biografia: "Karolína Plíšková (en la actualidad oficialmente Karolína Hrdličková, Louny, 21 de marzo de 1992). Sus padres son Radek y Martina Plíšková, y tiene una hermana gemela Kristýna, quien también es jugadora de tenis.", torneos: "Siendo una de las jugadores de la actualidad con mayor cantidad de torneos ganados, tanto de modo individual como en dobles, habiendo obtenido 12 y 5 títulos respectivamente.", curiosidad: "Su entrenadora desde 2018 es la extenista española Conchita Martínez. Posee un perro como mascota llamado Roger desde junio de 2017." },
      { id: 5, ranking: 5, nacionalidad: "Alemania", nombre: "Angelique Kerber", edad: 31, foto: "./assets/jugadoras/AngeliqueKerber.JPG", biografia: "Angelique Kerber (Bremen, Alemania Federal, 18 de enero de 1988). Sus padres son Sławomir Kerber y Beata, y tiene una hermana. Su madre es alemana y su padre es polaco de origen alemán. Empezó a jugar tenis a los tres años y posteriormente se unió al circuito junior, participando en giras a través de Alemania y de Europa.", torneos: "En total ha conseguido 12 títulos individuales de WTA, que incluyen sus 3 títulos de Grand Slam. Por otra parte, fue medallista de plata en la prueba individual de tenis en los Juegos Olímpicos de 2016. ", curiosidad: "Actualmente, es la embajadora de la marca Porsche. Asimismo, trabaja en colaboración con Adidas para el diseño y fabricación de su línea de ropa deportiva." },
      { id: 6, ranking: 6, nacionalidad: "Ucrania", nombre: "Elina Svitolina", edad: 24, foto: "./assets/jugadoras/ElinaSvitolina.JPG", biografia: "Elina Svitolina (Odesa, 12 de septiembre de 1994). Hija de Mijaylo Svitolin y Elena. Tiene un hermano, Julian. Reside en Járkov (Ucrania). Entrenada por Gabriel Urpi (2018).", torneos: "Siendo considerada como una de las jugadoras a participar en el cambio generacional de la rama femenil del tenis profesional, esta jugadora ha logrado conseguir la cantidad de 13 torneos de manera individual, así como de 2 en la modalidad de doles.", curiosidad: "En palabras de la ucraniana: «Adoro leer y aprender idiomas extranjeros. Además, hace poco que me convertí en una gran fanática del fútbol y actualmente estoy prestando bastante atención a la Premier League inglesa»" },
      { id: 7, ranking: 7, nacionalidad: "Holanda", nombre: "Kiki Bertens", edad: 27, foto: "./assets/jugadoras/KikiBertens.JPG", biografia: "Kiki Bertens (Wateringen, Países Bajos, 10 de diciembre de 1991). ", torneos: "Ha ganado 8 torneos de la WTA en categoría individual y 10 en dobles.", curiosidad: "A Bertens le diagnosticaron un tumor en su tiroides durante un test médico en Miami, hace dos años. Ella continuó jugando sin saber si era benigno o no, ya que los médicos no podían decírselo con seguridad, habiendo programado una operación para extirpárselo después de Roland Garros, pero tras pasar la fase previa, se metió en cuarta ronda y canceló su cirugía por miedo a los riesgos que podría tener, aunque los médicos le aconsejaron que lo extirpara." },
      { id: 8, ranking: 8, nacionalidad: "Estados Unidos", nombre: "Sloane Stephens", edad: 26, foto: "./assets/jugadoras/SloaneStephens.JPG", biografia: "Sloane Stephens (Coral Springs, Florida, Estados Unidos, 20 de marzo de 1993). ", torneos: "Ganadora de 6 torneos en la rama individual, siendo el más reconocido de estos el obtenido en el año 2017 en el US Open.", curiosidad: "En los cuartos de final del Abierto de Australia de 2013, Stephens derrotó a su compatriota Venus Williams para convertirse en la jugadora más joven, y la única adolescente, entre las Top 20." },
      { id: 9, ranking: 9, nacionalidad: "Australia", nombre: "Ashleigh Barty", edad: 22, foto: "./assets/jugadoras/AshleighBarty.JPG", biografia: "Ashleigh Barty (Ipswich, Australia, 24 de abril de 1996). ", torneos: "En el caso de la tenista australiana, su relación con el trirunfo de torneos se ha visto estancada al solo haber conseguido 4 títulos de 13 intentos en los que ha llegado a alguna final.", curiosidad: "Acumula cinco tíulos individuales y un título de dobles en el circuito ITF." },
      { id: 10, ranking: 10, nacionalidad: "Bielorrusia", nombre: "Aryna Sabalenka", edad: 20, foto: "./assets/jugadoras/ArynaSabalenka.JPG", biografia: "Aryna Sabalenka (Bielorrusia, 5 de mayo de 1998).", torneos: "Sabalenka saltó a la fama en 2017 tras llevar a Bielorrusia a la primera final de la historia de la Fed Cup junto a Aliaksandra Sasnovich. Hasta la fecha, ha ganado 3 títulos individuales WTA.", curiosidad: "Tenista más jóven en alcanzazr el top 20." },
      { id: 11, ranking: 11, nacionalidad: "Estados Unidos", nombre: "Serena Williams", edad: 37, foto: "./assets/jugadoras/SerenaWilliams.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 12, ranking: 12, nacionalidad: "Dinamarca", nombre: "Caroline Wozniacki", edad: 28, foto: "./assets/jugadoras/CarolineWozniacki.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 13, ranking: 13, nacionalidad: "Letonia", nombre: "Anastasija Sevastova", edad: 28, foto: "./assets/jugadoras/AnastasijaSevastova.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 14, ranking: 14, nacionalidad: "Estados Unidos", nombre: "Madison Keys", edad: 24, foto: "./assets/jugadoras/MadisonKeys.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 15, ranking: 15, nacionalidad: "Estonia", nombre: "Anett Kontaveit", edad: 23, foto: "./assets/jugadoras/AnettKontaveit.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 16, ranking: 16, nacionalidad: "China", nombre: "Qiang Wang", edad: 27, foto: "./assets/jugadoras/QiangWang.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 17, ranking: 17, nacionalidad: "Belgica", nombre: "Elise Mertens", edad: 23, foto: "./assets/jugadoras/EliseMertens.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 18, ranking: 18, nacionalidad: "Alemania", nombre: "Julia Goerges", edad: 30, foto: "./assets/jugadoras/JuliaGeorges.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 19, ranking: 19, nacionalidad: "España", nombre: "Garbiñe Muguruza", edad: 25, foto: "./assets/jugadoras/GarbiñeMuguruza.JPG", biografia: "", torneos: "", curiosidad: "" },
      { id: 20, ranking: 20, nacionalidad: "Suiza", nombre: "Belinda Bencic", edad: 22, foto: "./assets/jugadoras/BelindaBencic.JPG", biografia: "", torneos: "", curiosidad: "" }
    ];
    const INDIVIDUALES = [
      { id: 1, genero: "masculino", torneo: "Qatar ExxonMobil Open", bandera1:"../assets/banderas/italia.png", jugador1: "Jannik Sinner", bandera2: "../assets/banderas/hungria.png", jugador2: "Mate Valkuz", j1s1:6, j2s1:2, j1s2:0, j2s2:6, j1s3:6, j2s3:4, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 2, genero: "masculino", torneo: "Qatar ExxonMobil Open", bandera1:"../assets/banderas/serbia.png", jugador1: "Filip Krajinovic", bandera2: "../assets/banderas/italia.png", jugador2: "Andreas Seppi", j1s1:6, j2s1:2, j1s2:5, j2s2:7, j1s3:7, j2s3:5, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 3, genero: "masculino", torneo: "Qatar ExxonMobil Open", bandera1:"../assets/banderas/francia.png", jugador1: "Pierre-Hugues Herbert", bandera2: "../assets/banderas/belarus.png", jugador2: "Egor Fabbiano", j1s1:6, j2s1:3, j1s2:6, j2s2:2, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 4, genero: "masculino", torneo: "Qatar ExxonMobil Open", bandera1:"../assets/banderas/paises-bajos.png", jugador1: "Robin Haase", bandera2: "../assets/banderas/italia.png", jugador2: "Thomas Fabbiano", j1s1:6, j2s1:2, j1s2:5, j2s2:7, j1s3:7, j2s3:5, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 5, genero: "masculino", torneo: "Qatar ExxonMobil Open", bandera1:"../assets/banderas/alemania.png", jugador1: "Peter Gojowczyk", bandera2: "../assets/banderas/sudafrica.png", jugador2: "Lloyd Harris", j1s1:7, j2s1:5, j1s2:6, j2s2:4, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 6, genero: "masculino", torneo: "Brisbane International", bandera1:"../assets/banderas/argentina.png", jugador1: "Pablo Cuevas", bandera2: "../assets/banderas/alemania.png", jugador2: "Yannick Maden", j1s1:6, j2s1:3, j1s2:3, j2s2:6, j1s3:6, j2s3:4, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 7, genero: "masculino", torneo: "Brisbane International", bandera1:"../assets/banderas/eslovenia.png", jugador1: "Aljaz Bedene", bandera2: "../assets/banderas/nueva-zelandia.png", jugador2: "Bernard Tomic", j1s1:6, j2s1:4, j1s2:6, j2s2:3, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 8, genero: "masculino", torneo: "Brisbane International", bandera1:"../assets/banderas/hungria.png", jugador1: "Attila Balazs", bandera2: "../assets/banderas/polonia.png", jugador2: "Hubert Hurkacz", j1s1:6, j2s1:3, j1s2:6, j2s2:4, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 9, genero: "masculino", torneo: "Brisbane International", bandera1:"../assets/banderas/moldavia.png", jugador1: "Radu Albot", bandera2: "../assets/banderas/ucrania.png", jugador2: "Sergiy Stakhovsky", j1s1:7, j2s1:5, j1s2:6, j2s2:4, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 10, genero: "masculino", torneo: "Brisbane International", bandera1:"../assets/banderas/italia.png", jugador1: "Matteo Berrettini", bandera2: "../assets/banderas/kazajstan.png", jugador2: "Mikhail Kukushkin", j1s1:6, j2s1:4, j1s2:6, j2s2:4, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 11, genero: "masculino", torneo: "Tata Open Maharashtra", bandera1:"../assets/banderas/nueva-zelandia.png", jugador1: "John Millman", bandera2: "../assets/banderas/serbia.png", jugador2: "Miomir Kecmanovic", j1s1:6, j2s1:1, j1s2:6, j2s2:2, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 12, genero: "masculino", torneo: "Tata Open Maharashtra", bandera1:"../assets/banderas/serbia.png", jugador1: "Laslo Djre", bandera2: "../assets/banderas/austria.png", jugador2: "Ernests Gulbis", j1s1:6, j2s1:4, j1s2:5, j2s2:7, j1s3:7, j2s3:5, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 13, genero: "masculino", torneo: "Tata Open Maharashtra", bandera1:"../assets/banderas/francia.png", jugador1: "Pierre-Hugues Herbert", bandera2: "../assets/banderas/alemania.png", jugador2: "Matthias Bachinger", j1s1:7, j2s1:5, j1s2:6, j2s2:2, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 14, genero: "masculino", torneo: "Tata Open Maharashtra", bandera1:"../assets/banderas/italia.png", jugador1: "Matteo Berrettini", bandera2: "../assets/banderas/eslovenia.png", jugador2: "Aljaz Bedene", j1s1:7, j2s1:5, j1s2:6, j2s2:2, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 15, genero: "masculino", torneo: "Tata Open Maharashtra", bandera1:"../assets/banderas/serbia.png", jugador1: "Filip Krajinovic", bandera2: "../assets/banderas/moldavia.png", jugador2: "Radu Albot", j1s1:7, j2s1:5, j1s2:6, j2s2:4, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 16, genero: "femenino", torneo: "Mutua Madrid Open", bandera1:"../assets/banderas/republica-checa.png", jugador1: "Tereza Martincova", bandera2: "../assets/banderas/china.png", jugador2: "Kai-Lin Zhang", j1s1:6, j2s1:6, j1s2:6, j2s2:4, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 17, genero: "femenino", torneo: "Mutua Madrid Open", bandera1:"../assets/banderas/india.png", jugador1: "Karman Thandi", bandera2: "../assets/banderas/hong.png", jugador2: "Kwan Yau Ng", j1s1:6, j2s1:4, j1s2:6, j2s2:4, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 18, genero: "femenino", torneo: "Mutua Madrid Open", bandera1:"../assets/banderas/china.png", jugador1: "Ya-Hsuan Lee", bandera2: "../assets/banderas/japon.png", jugador2: "Ayano Shimizu", j1s1:6, j2s1:4, j1s2:6, j2s2:4, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 19, genero: "femenino", torneo: "Mutua Madrid Open", bandera1:"../assets/banderas/china.png", jugador1: "Yuxuan Zhang", bandera2: "../assets/banderas/china.png", jugador2: "Ya-Yi Yang", j1s1:6, j2s1:0, j1s2:6, j2s2:1, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 20, genero: "femenino", torneo: "Mutua Madrid Open", bandera1:"../assets/banderas/rumania.png", jugador1: "Elena-Gabriela Ruse", bandera2: "../assets/banderas/japon.png", jugador2: "Mayo Hibi", j1s1:7, j2s1:5, j1s2:2, j2s2:6, j1s3:6, j2s3:4, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 21, genero: "femenino", torneo: "Croatia Bol Open", bandera1:"../assets/banderas/australia.png", jugador1: "Lizette Cabrera", bandera2: "../assets/banderas/japon.png", jugador2: "Junri Namigata", j1s1:6, j2s1:4, j1s2:6, j2s2:3, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 22, genero: "femenino", torneo: "Croatia Bol Open", bandera1:"../assets/banderas/rusia.png", jugador1: "Olga Doroshina", bandera2: "../assets/banderas/tailandia.png", jugador2: "Peangtarn Plipuech", j1s1:6, j2s1:2, j1s2:6, j2s2:3, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 23, genero: "femenino", torneo: "Croatia Bol Open", bandera1:"../assets/banderas/corea-del-sur.png", jugador1: "Su Jeong Jang", bandera2: "../assets/banderas/japon.png", jugador2: "Momoko Kobori", j1s1:6, j2s1:1, j1s2:6, j2s2:4, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 24, genero: "femenino", torneo: "Croatia Bol Open", bandera1:"../assets/banderas/paises-bajos.png", jugador1: "Bibiane Schoofs", bandera2: "../assets/banderas/canada.png", jugador2: "Carol", j1s1:6, j2s1:3, j1s2:6, j2s2:2, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 25, genero: "femenino", torneo: "Croatia Bol Open", bandera1:"../assets/banderas/japon.png", jugador1: "Nao Hibino", bandera2: "../assets/banderas/india.png", jugador2: "Ankita Raina", j1s1:7, j2s1:5, j1s2:6, j2s2:1, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 26, genero: "femenino", torneo: "Mallorca Open", bandera1:"../assets/banderas/china.png", jugador1: "Yuxuan Zhang", bandera2: "../assets/banderas/india.png", jugador2: "Karman Thandi", j1s1:6, j2s1:2, j1s2:6, j2s2:2, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 27, genero: "femenino", torneo: "Mallorca Open", bandera1:"../assets/banderas/republica-checa.png", jugador1: "Tereza Martinicova", bandera2: "../assets/banderas/china.png", jugador2: "Ya-Hsuan Lee", j1s1:6, j2s1:3, j1s2:6, j2s2:0, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 28, genero: "femenino", torneo: "Mallorca Open", bandera1:"../assets/banderas/rumania.png", jugador1: "Elena-Gabriela Ruse", bandera2: "../assets/banderas/rusia.png", jugador2: "Olga Doroshina", j1s1:7, j2s1:5, j1s2:7, j2s2:5, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 29, genero: "femenino", torneo: "Mallorca Open", bandera1:"../assets/banderas/corea-del-sur.png", jugador1: "Su Jeong Jang", bandera2: "../assets/banderas/australia.png", jugador2: "Lizette Cabrera", j1s1:6, j2s1:4, j1s2:6, j2s2:4, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null},
      { id: 30, genero: "femenino", torneo: "Mallorca Open", bandera1:"../assets/banderas/china.png", jugador1: "Fang Ting Xun", bandera2: "../assets/banderas/china.png", jugador2: "Yingying Duan", j1s1:7, j2s1:5, j1s2:7, j2s2:5, j1s3:null, j2s3:null, j1s4:null, j2s4:null, j1s5:null, j2s5:null}
    ];

    const DOBLES = [
      {id:1, genero :"masculino", torneo:"Davis Cup Group II", bandera1:"../assets/banderas/alemania.png", jugador1:"Kevin Krawietz", bandera2:"../assets/banderas/alemania.png", jugador2:"Andreas Mies", bandera3:"../assets/banderas/moldavia.png", jugador3:"Radu Albot", bandera4:"../assets/banderas/georgia.png", jugador4:"Nikoloz Basilashvili", e1s1:6, e2s1:3, e1s2:6, e2s2:3, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:2, genero :"masculino", torneo:"Davis Cup Group II", bandera1:"../assets/banderas/brasil.png", jugador1:"Marcelo Demoliner", bandera2:"../assets/banderas/india.png", jugador2:"Divij Sharan", bandera3:"../assets/banderas/suecia.png", jugador3:"Robert Lindstedt", bandera4:"../assets/banderas/pakistan.png", jugador4:"Aisam-Ul-Haq Qureshi", e1s1:6, e2s1:3, e1s2:4, e2s2:6, e1s3:11, e2s3:9, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:3, genero :"masculino", torneo:"Davis Cup Group II", bandera1:"../assets/banderas/rusia.png", jugador1:"Wesley Koolhof", bandera2:"../assets/banderas/nueva-zelandia.png", jugador2:"Marcus Daniell", bandera3:"../assets/banderas/polonia.png", jugador3:"Hubert Hurkacz", bandera4:"../assets/banderas/francia.png", jugador4:"Fabrice Martin", e1s1:6, e2s1:2, e1s2:6, e2s2:3, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:4, genero :"masculino", torneo:"Davis Cup Group II", bandera1:"../assets/banderas/alemania.png", jugador1:"Andre Begemann", bandera2:"../assets/banderas/austria.png", jugador2:"Ernests Gulbis", bandera3:"../assets/banderas/republica-checa.png", jugador3:"Roman Jebavy", bandera4:"../assets/banderas/argentina.png", jugador4:"Andres Molteni", e1s1:6, e2s1:4, e1s2:7, e2s2:5, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:5, genero :"masculino", torneo:"Davis Cup Group II", bandera1:"../assets/banderas/paises-bajos.png", jugador1:"Robin Haase", bandera2:"../assets/banderas/dinamarca.png", jugador2:"Frederik Nielsen", bandera3:"../assets/banderas/hungria.png", jugador3:"Gabor Borsos", bandera4:"../assets/banderas/hungria.png", jugador4:"Peter Nagy", e1s1:6, e2s1:2, e1s2:6, e2s2:4, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:6, genero :"masculino", torneo:"Grand Prix Hassan II", bandera1:"../assets/banderas/paises-bajos.png", jugador1:"Jean-Julien Rojer", bandera2:"../assets/banderas/rumania.png", jugador2:"Horia Tecau", bandera3:"../assets/banderas/espana.png", jugador3:"David Marrero", bandera4:"../assets/banderas/espana.png", jugador4:"Fernando Verdasco", e1s1:6, e2s1:3, e1s2:7, e2s2:5, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:7, genero :"masculino", torneo:"Grand Prix Hassan II", bandera1:"../assets/banderas/finlandia.png", jugador1:"Henri Kontinen", bandera2:"../assets/banderas/australia.png", jugador2:"John Peers", bandera3:"../assets/banderas/argentina.png", jugador3:"Maximo Gonalez", bandera4:"../assets/banderas/argentina.png", jugador4:"Horacio Zeballos", e1s1:7, e2s1:5, e1s2:6, e2s2:4, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:8, genero :"masculino", torneo:"Grand Prix Hassan II", bandera1:"../assets/banderas/sudafrica.png", jugador1:"Raven Klaasen", bandera2:"../assets/banderas/reino-unido.png", jugador2:"Joe Salisbury", bandera3:"../assets/banderas/espana.png", jugador3:"Marcel Granollers", bandera4:"../assets/banderas/espana.png", jugador4:"Marc Lopez", e1s1:6, e2s1:2, e1s2:3, e2s2:6, e1s3:5, e2s3:4, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:9, genero :"masculino", torneo:"Grand Prix Hassan II", bandera1:"../assets/banderas/espana.png", jugador1:"Pablo Carreno Busta", bandera2:"../assets/banderas/espana.png", jugador2:"Feliciano Lopez", bandera3:"../assets/banderas/croacia.png", jugador3:"Nikola Mektic", bandera4:"../assets/banderas/croacia.png", jugador4:"Franko Skugor", e1s1:6, e2s1:3, e1s2:6, e2s2:4, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:10, genero :"masculino", torneo:"Grand Prix Hassan II", bandera1:"../assets/banderas/austria.png", jugador1:"Oliver Marach", bandera2:"../assets/banderas/croacia.png", jugador2:"Mate Pavic", bandera3:"../assets/banderas/japon.png", jugador3:"Kei Nishikori", bandera4:"../assets/banderas/argentina.png", jugador4:"Diego Schwartzman", e1s1:5, e2s1:7, e1s2:6, e2s2:4, e1s3:7, e2s3:5, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:11, genero :"femenino", torneo:"Bucharest Open", bandera1:"../assets/banderas/rusia.png", jugador1:"Anastasia Pavlyuchencova", bandera2:"../assets/banderas/republica-checa.png", jugador2:"Lucie Safarova", bandera3:"../assets/banderas/estados-unidos.png", jugador3:"Raquel Atawo", bandera4:"../assets/banderas/eslovenia.png", jugador4:"Katarina Srebotnik", e1s1:6, e2s1:0, e1s2:6, e2s2:2, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:12, genero :"femenino", torneo:"Bucharest Open", bandera1:"../assets/banderas/canada.png", jugador1:"Gabriela Dabrowski", bandera2:"../assets/banderas/letonia.png", jugador2:"Jelena Ostapenko", bandera3:"../assets/banderas/suiza.png", jugador3:"Belinda Bencic", bandera4:"../assets/banderas/polonia.png", jugador4:"Alicja Rosolska", e1s1:2, e2s1:6, e1s2:7, e2s2:5, e1s3:6, e2s3:4, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:13, genero :"femenino", torneo:"Bucharest Open", bandera1:"../assets/banderas/rusia.png", jugador1:"Ana Blinkova", bandera2:"../assets/banderas/georgia.png", jugador2:"Oksana Kalashnikova", bandera3:"../assets/banderas/croacia.png", jugador3:"Darija Jurak", bandera4:"../assets/banderas/rumania.png", jugador4:"Raluca Olaru", e1s1:3, e2s1: 6, e1s2:6, e2s2:2, e1s3:4, e2s3:6, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:14, genero :"femenino", torneo:"Bucharest Open", bandera1:"../assets/banderas/alemania.png", jugador1:"Mona Barthel", bandera2:"../assets/banderas/alemania.png", jugador2:"Anna-Lena Friedsam", bandera3:"../assets/banderas/luxemburgo.png", jugador3:"Mandy Minella", bandera4:"../assets/banderas/alemania.png", jugador4:"Andera Petkovic", e1s1:6, e2s1:3, e1s2:3, e2s2:6, e1s3:4, e2s3:6, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:15, genero :"femenino", torneo:"Bucharest Open", bandera1:"../assets/banderas/rusia.png", jugador1:"Anastasia Pablyuchenkova", bandera2:"../assets/banderas/republica-checa.png", jugador2:"Lucie Safarova", bandera3:"../assets/banderas/rusia.png", jugador3:"Anna Blinkova", bandera4:"../assets/banderas/georgia.png", jugador4:"Oksana Kalashnikova", e1s1:6, e2s1: 4, e1s2:7, e2s2:5, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:16, genero :"femenino", torneo:"Palermo Ladies Open", bandera1:"../assets/banderas/alemania.png", jugador1:"Mona Barthel", bandera2:"../assets/banderas/alemania.png", jugador2:"Anna-Lena Friedsam", bandera3:"../assets/banderas/canada.png", jugador3:"Gabriela Dabrowski", bandera4:"../assets/banderas/letonia.png", jugador4:"Jelena Ostapenko", e1s1:4, e2s1:6, e1s2:6, e2s2:2, e1s3:4, e2s3:6, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:17, genero :"femenino", torneo:"Palermo Ladies Open", bandera1:"../assets/banderas/chile.png", jugador1:"Alexa Guarachi", bandera2:"../assets/banderas/estados-unidos.png", jugador2:"Sabrina Santamarina", bandera3:"../assets/banderas/suiza.png", jugador3:"Xenia Knoll", bandera4:"../assets/banderas/hungria.png", jugador4:"Fanny Stollar", e1s1:4, e2s1:6, e1s2:6, e2s2:4, e1s3:4, e2s3:6, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:18, genero :"femenino", torneo:"Palermo Ladies Open", bandera1:"../assets/banderas/suecia.png", jugador1:"Cornelia Lister", bandera2:"../assets/banderas/republica-checa.png", jugador2:"Renata Voracova", bandera3:"../assets/banderas/rusia.png", jugador3:"Margarita Gasparyan", bandera4:"../assets/banderas/grecia.png", jugador4:"Maria Sakkari", e1s1:4, e2s1:6, e1s2:4, e2s2:6, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:19, genero :"femenino", torneo:"Palermo Ladies Open", bandera1:"../assets/banderas/australia.png", jugador1:"Monic Adamczak", bandera2:"../assets/banderas/australia.png", jugador2:"Jessica Moore", bandera3:"../assets/banderas/republica-checa.png", jugador3:"Barbora Strycova", bandera4:"../assets/banderas/republica-checa.png", jugador4:"Maketa Vondrousova", e1s1:7, e2s1:5, e1s2:6, e2s2:4, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null},
      {id:20, genero :"femenino", torneo:"Palermo Ladies Open", bandera1:"../assets/banderas/hungria.png", jugador1:"Timea Babos", bandera2:"../assets/banderas/francia.png", jugador2:"Kristina Mladenovic", bandera3:"../assets/banderas/rumania.png", jugador3:"Andreea Mitu", bandera4:"../assets/banderas/rusia.png", jugador4:"Alejandra Panova", e1s1:7, e2s1:5, e1s2:6, e2s2:3, e1s3:null, e2s3:null, e1s4:null, e2s4:null, e1s5:null, e2s5:null}


    ];
    const TORNEOS = [
      { id: 1, nombreTorneo: "ASB Classic", nacionalidad: "Auckland, New Zealand", fechaInicio: "2019.01.07", fechaFinal: "2019.01.12", tipoCancha: "Dura Exterior", descripcion: "El ASB Classic es el evento deportivo profesional masculino más importante de Nueva Zelanda y se celebra en Auckland desde 1956.",financiamientoTotal: "$589,680", titulo: "El Orgullo De Nueva Zelanda", informacion: "El ASB Classic es el evento deportivo profesional masculino más importante de Nueva Zelanda y se celebra en Auckland desde 1956. Jugado en la semana anterior al Abierto de Australia, el evento ATP World Tour 250 es una parada crucial en la preparación para el primer Grand Slam del año. torneo. David Ferrer llegó a las semifinales de Melbourne en 2011 y '13 luego de ganar dos de sus cuatro títulos de Auckland." ,foto: "../../../assets/img/estadio-8.jpg"},
      { id: 2, nombreTorneo: "Sydney International", nacionalidad: "Sydney, Australia", fechaInicio: "2019.01.06", fechaFinal: "2019.01.12",tipoCancha: "Dura Exterior", descripcion: "El Internacional de Sydney tiene una rica historia, que se remonta a 1885 cuando los funcionarios coloniales lo utilizaron como un medio para seleccionar el equipo de la Copa Davis.", titulo: "Sydney, Internacional", financiamientoTotal: "$589,680", informacion: "El Internacional de Sydney tiene una rica historia, que se remonta a 1885 cuando los funcionarios coloniales lo utilizaron como un medio para seleccionar el equipo de la Copa Davis. Hoy, Sydney recibe a los mejores jugadores masculinos y femeninos del mundo en la semana anterior al Abierto de Australia. Lleyton Hewitt emocionó a los fanáticos de su ciudad natal al ganar títulos en cuatro apariciones consecutivas en torneos, de 2000-01 y 2004-05. El australiano Bernard Tomic ganó su primer título ATP World Tour aquí en 2013." ,foto: "../../../assets/img/estadio-7.jpg" },
      { id: 3, nombreTorneo: "Millennium Estoril Open", nacionalidad: "Estoril, Portugal", fechaInicio: "2019.04.29", fechaFinal: "2019.05.05", tipoCancha: "Dura Exterior",descripcion: "El Millennium Estoril Open asegura el futuro de un torneo portugués en el calendario del Tour ATP, una tradición desde 1990.",financiamientoTotal: "€586,140", titulo: "Una Nueva Era En Estoril", informacion: "El Millennium Estoril Open asegura el futuro de un torneo portugués en el calendario ATP Tour, una tradición desde 1990. El país debutó su nuevo torneo ATP 250 en canchas de arcilla en el Clube de Ténis do Estoril en 2015. En asociación con el Municipio de Cascais El torneo verá a los fanáticos disfrutar de una mayor proximidad con los jugadores y la acción en la cancha. La edición 2019 del torneo está programada del 29 de abril al 5 de mayo." ,foto: "../../../assets/img/estadio-9.jpg"},
      { id: 4, nombreTorneo: "Australian Open", nacionalidad: "Melbourne, Australia", fechaInicio: "2019.01.14", fechaFinal:"2019.01.12", tipoCancha: "Dura Exterior",descripcion: "La temporada de Grand Slam comienza en el Abierto de Australia, donde los fanáticos de todo el mundo buscan el tenis estelar y un ambiente relajado en Melbourne.",financiamientoTotal: "$589,680", titulo: "Comenzando La Temporada De Grand Slam", informacion: "La temporada de Grand Slam comienza en el Abierto de Australia, donde los fanáticos de todo el mundo buscan el tenis estelar y un ambiente relajado en Melbourne. En los últimos tiempos, el Grand Slam de Asia / Pacífico ha sido un campo de juegos para los Cuatro Grandes, con Novak Djokovic (7; 2008, '11 -'13, '15 -'16, '19), Roger Federer (6; 2004 , '06 -'07, '10, '17 -'18) y Rafael Nadal (2009) habiendo ganado todos menos dos de los títulos del Abierto de Australia desde 2004. La rusa Marat Safin (2005) y el suizo Stan Wawrinka (2014) rompieron el racha. Brit Andy Murray ha finalizado subcampeón cinco veces." ,foto: "../../../assets/img/estadio-10_australia_Open.jpg"},
      { id: 5, nombreTorneo: "Davis Cup Qualifiers", nacionalidad: "Multiple Locations", fechaInicio: "2019.02.01", fechaFinal: "2019.02.02", tipoCancha: "Dura Exterior",descripcion: "Del 1 al 2 de febrero de 2019, 24 naciones competirán por 12 puestos clasificatorios en la Copa Davis.",financiamientoTotal: "     ", titulo: "Copa Davis 2019 por BNP Paribas Qualifiers", informacion: "Del 1 al 2 de febrero de 2019, 24 naciones competirán por 12 puestos clasificatorios en las finales de la Copa Davis de Madrid. Croacia, Francia, España, Estados Unidos, Argentina y Gran Bretaña ya se han clasificado para las finales." ,foto: "../../../assets/img/estadio-11_Davis_Cup_Qualifiers.jpg"},
      { id: 6, nombreTorneo: "Cordoba Open", nacionalidad: "Cordoba, Argentina", fechaInicio: "2019.02.04", fechaFinal: "2019.02.10", tipoCancha: "Dura Exterior",descripcion: "El Abierto de Córdoba hace su debut en el ATP Tour en 2019.",financiamientoTotal: "$589,680", titulo: "Córdoba Lanza Golden Swing", informacion: "El Cordoba Open hace su debut en el ATP Tour en 2019. Es el primer torneo de tierra batida de la temporada y también la primera etapa del swing de cinco torneos en América Latina, acertadamente acuñado el 'Golden Swing'. La ciudad de Córdoba, a 435 millas al noroeste de Buenos Aires, ha sido sede de varios eventos deportivos internacionales, incluidos los partidos de clasificación de fútbol de la Copa Mundial de la FIFA." ,foto: "../../../assets/img/estadio-12_Cordoba_Open.jpg"},
      { id: 7, nombreTorneo: "Open Sud de France", nacionalidad: "Montpellier, France", fechaInicio: "2019.02.04", fechaFinal: "2019.02.10", tipoCancha: "Bajo Techo",descripcion: "Montpellier, una de las ciudades de más rápido crecimiento en Francia durante los últimos 25 años, recibió su primer torneo ATP World Tour 250 a finales de octubre de 2010.",financiamientoTotal: "€586,140" , titulo: "Montpellier Prospera En La Temporada Interior Europea De Febrero", informacion: "Montpellier, una de las ciudades de más rápido crecimiento en Francia durante los últimos 25 años, organizó su primer torneo ATP World Tour 250 a finales de octubre de 2010. Dos años después, el evento cubierto en pista dura se trasladó a un lugar de usos múltiples llamado Sud de France Arena, que tiene una capacidad total de 14,000 y capacidad para 7,500 durante el torneo." ,foto: "../../../assets/img/estadio-13_Open_Sud_de_France.jpg"},
      { id: 8, nombreTorneo: "Rio Open presented by Claro", nacionalidad: "Rio de Janeiro, Brazil", fechaInicio: "2019.02.18", fechaFinal:"2019.02.24", tipoCancha: "Arcilla",descripcion: "El Abierto de Río presentado por Claro se lleva a cabo en las ocho canchas de arcilla, incluido un Estadio de 6.200 asientos, del Jockey Club Brasileiro.",financiamientoTotal: "$1,937,740" , titulo: "Río Prepara El Escenario Para El Primer Evento 500 De Brasil", informacion: "El Abierto de Río presentado por Claro se lleva a cabo en las ocho canchas de arcilla, incluido un Estadio de 6.200 asientos, del Jockey Club Brasileiro. Rafael Nadal ganó la edición inaugural en 2014 antes de que David Ferrer triunfara en 2015. Los incondicionales de la pista de arcilla Pablo Cuevas, Dominic Thiem y Diego Schwartzman obtuvieron los títulos en 2016, 2017 y 2018, respectivamente." ,foto: "../../../assets/img/estadio-14_Rio_Open_presented_by_Claro.jpg"},
      { id: 9, nombreTorneo: "Argentina Open", nacionalidad: "Buenos Aires, Argentina", fechaInicio: "2019.02.11", fechaFinal:"2019.02.17", tipoCancha: "Arcilla",descripcion: "El Abierto de Argentina es la segunda parada del 'Golden Swing' latinoamericano, y se disputa sobre tierra batida en el Buenos Aires Lawn Tennis Club, conocida como la 'Catedral del tenis argentino'.",financiamientoTotal: "$673,135", titulo: "Argentinos En Casa En La 'Catedral' De Buenos Aires", informacion: "El Abierto de Argentina es la segunda parada del 'Golden Swing' latinoamericano, y se disputa sobre tierra batida en el Buenos Aires Lawn Tennis Club, conocida como la 'Catedral del tenis argentino'. Los campeones argentinos incluyen a Guillermo Coria, Gastón Gaudio, Juan Mónaco y David Nalbandian." ,foto: "../../../assets/img/estadio-15_Argentina_Open.jpg" },
      { id: 10, nombreTorneo: "New York Open", nacionalidad: "New York, NY, U.S.A", fechaInicio: "2019.02.11", fechaFinal: "2019.02.17", tipoCancha: "Bajo Techo",descripcion: "El New York Open, un evento ATP World Tour 250 se lleva a cabo en NYCB LIVE, sede del Nassau Veterans Memorial Coliseum.",financiamientoTotal: "$777,385", titulo: "Long Island Continúa Con La Tradición", informacion: "El New York Open, un evento ATP World Tour 250 se lleva a cabo en NYCB LIVE, sede del Nassau Veterans Memorial Coliseum. En 2018, el torneo se trasladó de Memphis a Long Island, asegurando la continuación de uno de los torneos de mayor duración del ATP World Tour en los Estados Unidos." ,foto: "../../../assets/img/estadio-16_New_York_Open.jpg" },
      { id: 11, nombreTorneo: "ABN AMRO World Tennis ", nacionalidad: "Rotterdam, Netherlands", fechaInicio: "2019.02.11", fechaFinal: "2019.02.17", tipoCancha: "Bajo Techo",descripcion: "La primera edición del ABN AMRO World Tennis Tournament, celebrada en 1974, fue ganada por el tenista holandés Tom Okker.",financiamientoTotal: "€2,098,480", titulo: "Dutch Titleist Due In Rotterdam", informacion: "La primera edición del ABN AMRO World Tennis Tournament, celebrada en 1974, fue ganada por el tenista holandés Tom Okker. Los aficionados al tenis en los Países Bajos tuvieron que esperar hasta 1995 para que otro holandés, Richard Krajicek, fuera titular en el evento de pista dura bajo techo. Los ganadores en los años intermedios han incluido jugadores ilustres, como Arthur Ashe, Jimmy Connors, Björn Borg, Boris Becker y Stefan Edberg. Desde entonces, estrellas, como Roger Federer, Yevgeny Kafelnikov, Lleyton Hewitt y Andy Murray, han levantado el trofeo." ,foto: "../../../assets/img/estadio-17_ABN_AMRO_World_Tennis.jpg"  },
      { id: 12, nombreTorneo: "Davis Cup Group II", nacionalidad: "Multiple Locations", fechaInicio: "2019.04.05",  fechaFinal: "2019.04.06", tipoCancha: "Multiple",descripcion: "Del 5 al 6 de abril de 2019, las naciones competirán en los empates del Grupo II en tres zonas regionales: América, Asia / Oceanía y Europa / África.",financiamientoTotal: " ", titulo: "Copa Davis 2019 por BNP Paribas Grupo II", informacion: "Del 5 al 6 de abril de 2019, las naciones competirán en los empates del Grupo II en tres zonas regionales: América, Asia / Oceanía y Europa / África." ,foto: "../../../assets/img/estadio-18_Davis_Cup_Group_II.jpg"  },
      { id: 13, nombreTorneo: "Fayez Sarofim & Co. U.S. Men's Clay Court Championship", nacionalidad: "Houston, TX, U.S.A.", fechaInicio: "2019.04.08", fechaFinal: "2019.04.14", tipoCancha: "Arcilla",descripcion: "El Campeonato de Corte de Arcilla Masculina de los Estados Unidos comenzó en 1910 en Omaha con la idea de alentar el establecimiento de más canchas de arcilla en el Oeste.",financiamientoTotal: "$652,245", titulo: "Lone Star State es el anfitrión del Campeonato de Arcilla Masculina de los Estados Unidos", informacion: "El Campeonato de Corte de Arcilla Masculina de los Estados Unidos comenzó en 1910 en Omaha con la idea de alentar el establecimiento de más canchas de arcilla en el Oeste. Desde entonces, el torneo se ha disputado en numerosas ciudades de los Estados Unidos, antes de establecerse en su ubicación actual de Houston en 2001. Es el único evento ATP Tour en los EE. UU. Disputado en tierra batida." ,foto: "../../../assets/img/estadio-19_Fayez_Sarofim_&_Co._U.S._Men's_Clay_Court_Championship.jpg" },
      { id: 14, nombreTorneo: "Grand Prix Hassan II", nacionalidad: "Marrakech, Morocco", fechaInicio: "2019.04.08",  fechaFinal: "2019.04.14", tipoCancha: "Arcilla",descripcion: "El Gran Premio Hassan II se inauguró como un evento ATP Challenger en 1984 y como un torneo ATP Tour en 1990.",financiamientoTotal: "€586,140", titulo: "Una Parada Real En Marruecos", informacion: "El Gran Premio Hassan II se inauguró como un evento ATP Challenger en 1984 y como un torneo ATP Tour en 1990. El torneo está financiado en su totalidad por el rey Mohammed VI de Marruecos. Marrakech, que se mudó de Casablanca en 2016, es la única parada del ATP Tour en el continente africano. Dos marroquíes han ganado el título en su país de origen: Hicham Arazi en 1997 y Younes El Aynaoui en 2002." ,foto: "../../../assets/img/estadio-20_Grand_Prix_Hassan_II.jpg"  },
      { id: 15, nombreTorneo: "Rolex Monte-Carlo Masters", nacionalidad: "Monte Carlo, Monaco", fechaInicio: "2019.04.14",  fechaFinal: "2019.04.21", tipoCancha: "Arcilla",descripcion: "El Rolex Monte-Carlo Masters, que celebró su centenario en 2006, es el primero de los tres torneos ATP Masters 1000 que se juegan en tierra batida.",financiamientoTotal: "€5,585,030", titulo: "La Gema Del Mediterraneo", informacion: "El Rolex Monte-Carlo Masters, que celebró su centenario en 2006, es el primero de los tres torneos ATP Masters 1000 que se juegan en tierra batida. El torneo es un jugador y favorito de los fanáticos debido a su magnífica ubicación, el Club de Campo Monte-Carlo y la larga tradición de campeones. El nadador español Rafael Nadal ha ganado 11 títulos en el evento, incluido un récord de Open-Era con ocho títulos sucesivos entre 2005-2012. La edición 2019 del torneo se llevará a cabo del 15 al 21 de abril." ,foto: "../../../assets/img/estadio-21_Rolex_Monte-Carlo_Masters.jpg" },
      { id: 16, nombreTorneo: "Barcelona Open Banc Sabadell", nacionalidad: "Barcelona, Spain", fechaInicio: "2019.04.22",  fechaFinal: "2019.04.28", tipoCancha: "Arcilla",descripcion: "El Barcelona Open Banc Sabadell, Trofeo Conde de Godo, se lleva a cabo en el Real Club de Tenis Barcelona-1899, el club de tenis más antiguo de España, desde 1953.",financiamientoTotal: "€2,746,455", titulo: "Un escenario histórico en barcelona", informacion: "El Barcelona Open Banc Sabadell, Trofeo Conde de Godo, se lleva a cabo en el Real Club de Tenis Barcelona-1899, el club de tenis más antiguo de España, desde 1953. El torneo de canchas de arcilla ATP 500 es uno de los eventos más importantes del tenis español. y en el calendario social barcelonés. Los españoles han ganado 14 de las últimas 16 ediciones, incluyendo un récord de 11 victorias para Rafael Nadal." ,foto: "../../../assets/img/estadio-22_Barcelona_Open_Banc_Sabadell.jpg" },
      { id: 17, nombreTorneo: "Chengdu Open", nacionalidad: "Chengdu, China", fechaInicio: "2019.09.23",  fechaFinal: "2019.09.29", tipoCancha: "Dura Exterior",descripcion: "El Chengdu Open, que debutó en 2016, se une a Zhuhai, Beijing y Shanghai como anfitriones chinos durante el swing asiático del ATP Tour.",financiamientoTotal: "$1,213,295", titulo: "Una de las cuatro paradas ATP Tour en China", informacion: "El Chengdu Open, que debutó en 2016, se une a Zhuhai, Beijing y Shanghai como anfitriones chinos durante el swing asiático del ATP Tour. El lugar en Chengdu cuenta con una instalación moderna con una capacidad de 6,000 canchas centrales, dos canchas de exhibición adicionales con 2,000 asientos cada una, y un total de 20 canchas duras y 12 canchas cubiertas." ,foto: "../../../assets/img/estadio-23_Chengdu_Open.jpg" },
      { id: 18, nombreTorneo: "Zhuhai Championships", nacionalidad: "Zhuhai, China", fechaInicio: "2019.09.23", fechaFinal: "2019.09.29", tipoCancha: "Dura Exterior",descripcion: "La ciudad de Zhuhai ha organizado con éxito un evento ATP Challenger Tour y WTA Elite Trophy en sus instalaciones de tenis de clase mundial, y en 2019 recibe un evento ATP Tour.",financiamientoTotal: "$1,000,000", titulo: "Zhuhai organiza el evento ATP Tour en 2019", informacion: "La ciudad de Zhuhai ha organizado con éxito un evento ATP Challenger Tour y WTA Elite Trophy en sus instalaciones de tenis de clase mundial, y en 2019 recibe un evento ATP Tour. Celebrado del 23 al 29 de septiembre, el Campeonato de Zhuhai es la parada de apertura de las tres semanas de swing asiático junto con el Abierto de Chengdu." ,foto: "../../../assets/img/estadio-24_Zhuhai_Championships.jpg" },
      { id: 19, nombreTorneo: "China Open", nacionalidad: "Beijing, China", fechaInicio: "2019.09.30",  fechaFinal: "2019.10.06", tipoCancha: "Dura Exterior",descripcion: "El Centro Olímpico de Tenis Verde de Beijing, construido para los Juegos Olímpicos de 2008, es el lugar para el Abierto de China.",financiamientoTotal: "$3,666,275", titulo: "ATP Elite Compite En Olympic Grounds", informacion: "El Centro Olímpico de Tenis Verde de Beijing, construido para los Juegos Olímpicos de 2008, es el lugar para el Abierto de China. En 2011, el centro se expandió a 11 canchas. El lugar también cuenta con un estadio de 15,000 asientos con un techo retráctil, llamado Diamond Court debido a su parecido. El centro de tenis emplea tecnología de refrigeración por aire de la era espacial para beneficiar a los jugadores y espectadores." ,foto: "../../../assets/img/estadio-25_China_Open.jpg" },
      { id: 20, nombreTorneo: "Rakuten Japan Open Tennis Championships", nacionalidad: "Tokyo, Japan", fechaInicio: "2019.09.30",  fechaFinal: "2019.10.06", tipoCancha: "Bajo Techo",descripcion: "El Rakuten Japan Open Tennis Championships es el torneo ATP Tour más antiguo de Asia, celebrado por primera vez en 1972.",financiamientoTotal: "$2,046,340", titulo: "El tenis asiático tiene raíces en la tierra del sol naciente", informacion: "El Rakuten Japan Open Tennis Championships es el torneo ATP Tour más antiguo de Asia, celebrado por primera vez en 1972. El torneo ATP 500 se juega en el Ariake Colosseum, un amplio centro de tenis con 48 canchas y un estadio con uno de los primeros techos retráctiles. en el tenis En preparación para los Juegos Olímpicos de 2020, el evento de 2018 se celebró en el interior en el Musushino Forest Sport Plaza. Kei Nishikori de Japón ganó los títulos de 2012 y 2014." ,foto: "../../../assets/img/estadio-26_Rakuten_Japan_Open_Tennis_Championships.jpg" }
    ];
    return { JUGADORES, JUGADORAS, INDIVIDUALES, DOBLES, TORNEOS };
  }
}