export class Competencias {
    constructor(
        public id1: number,
        public tipoCompetencia1?: string,
        public idTorneo1?: number,
        public cupo1?: number,
        public categoria1?: string,
        public costo1?: number,
        public primero1?: string,
        public segundo1?: string,
        public tercero1?: string,

        public id2?: number,
        public tipoCompetencia2?: string,
        public idTorneo2?: number,
        public cupo2?: number,
        public categoria2?: string,
        public costo2?: number,
        public primero2?: string,
        public segundo2?: string,
        public tercero2?: string,

        public id3?: number,
        public tipoCompetencia3?: string,
        public idTorneo3?: number,
        public cupo3?: number,
        public categoria3?: string,
        public costo3?: number,
        public primero3?: string,
        public segundo3?: string,
        public tercero3?: string,

        public id4?: number,
        public tipoCompetencia4?: string,
        public idTorneo4?: number,
        public cupo4?: number,
        public categoria4?: string,
        public costo4?: number,
        public primero4?: string,
        public segundo4?: string,
        public tercero4?: string,
    ){}
}
